export enum IssueUnits {
  TABS = 'TAB',
  CAPS = 'CAP',
  PFI = 'PFI',
  OR_LIQUID = 'OR Liq',
  IMP = 'IMP',
  INJ = 'INJ',
  SODF = 'SODF',
  CONC = 'CONC',
  SOL = 'SOL',
  SOL_INJ = 'Sol for INJ',
  GRA = 'GRA',
  OR_POWER = 'OR Pow',
  OR_PELLET = 'OR Pel',
  VAG_TAB = 'VAG Tab',
  ORO_SOL = 'ORO Sol',
  REC_GEL = 'REC Gel',
  CRE = 'CRE',
  OIN = 'OIN',
  LOT = 'LOT',
  PAS = 'PAS',
  TRO_APP = 'Tro APP',
  EYE_DROPS = 'EYE Dro',
  TES_STR = 'Tes STR',
  GEL = 'GEL',
  INJ_IV = 'INJ (IV)',
  COP = 'COP',
}
