export const DOSE_FORMS = [
  'Tablet',
  'Tablets',
  'Capsule',
  'PFI',
  'Oral Liquid',
  'Implant',
  'Injection',
  'SODF',
  'Concentrate',
  'Solution',
  'Solution for Injection',
  'Granules',
  'Oral Powder',
  'Oral Pellets',
  'Vaginal Tablet',
  'Oromucosal solution',
  'Rectal Gel',
  'Cream',
  'Ointment',
  'Lotion',
  'Paste',
  'Tropical Application',
  'Eye drops',
  'Test Strip',
  'Gel',
  'Injection(IV)',
  'Co-pack',
];
